// ==========================================================
// src/database/seed/seedData.ts
// بيانات تجريبية واقعية مناسبة للسوق المصري
// ==========================================================

export const INITIAL_FEATURES = [
  { id: "dashboard", name_ar: "لوحة التحكم", description_ar: "نظرة عامة وإحصائيات سريعة", is_core: 1, is_enabled: 1 },
  { id: "products", name_ar: "المنتجات", description_ar: "إدارة المنتجات والأسعار والأكواد", is_core: 1, is_enabled: 1 },
  { id: "categories", name_ar: "التصنيفات", description_ar: "تقسيم المنتجات إلى مجموعات", is_core: 1, is_enabled: 1 },
  { id: "inventory", name_ar: "المخزون", description_ar: "متابعة الكميات وسجل حركات المخزون", is_core: 1, is_enabled: 1 },
  { id: "sales", name_ar: "المبيعات", description_ar: "شاشة بيع سريعة (POS) وإصدار فواتير", is_core: 1, is_enabled: 1 },
  { id: "purchases", name_ar: "المشتريات", description_ar: "تسجيل فواتير الشراء وزيادة المخزون", is_core: 0, is_enabled: 1 },
  { id: "suppliers", name_ar: "الموردين", description_ar: "بيانات الموردين وأرصدتهم وسجل المشتريات", is_core: 0, is_enabled: 1 },
  { id: "customers", name_ar: "العملاء", description_ar: "بيانات العملاء والأرصدة والبيع الآجل", is_core: 0, is_enabled: 1 },
  { id: "expenses", name_ar: "المصروفات", description_ar: "تسجيل المصاريف اليومية وتأثيرها على صافي الربح", is_core: 0, is_enabled: 1 },
  { id: "barcode", name_ar: "الباركود", description_ar: "توليد وطباعة والبحث بالباركود", is_core: 0, is_enabled: 1 },
  { id: "reports", name_ar: "التقارير", description_ar: "تقارير المبيعات والأرباح والمخزون", is_core: 0, is_enabled: 1 },
  { id: "users", name_ar: "المستخدمين والصلاحيات", description_ar: "إدارة الموظفين وأدوارهم وصلاحياتهم", is_core: 0, is_enabled: 1 },
  { id: "activity_log", name_ar: "سجل النشاط", description_ar: "تتبع كل العمليات الحساسة في النظام", is_core: 0, is_enabled: 1 },
  { id: "notifications", name_ar: "الإشعارات", description_ar: "تنبيهات انخفاض المخزون والعمليات الهامة", is_core: 0, is_enabled: 1 },
  { id: "backup", name_ar: "النسخ الاحتياطي", description_ar: "حفظ واسترجاع قاعدة البيانات بأمان", is_core: 1, is_enabled: 1 },
  { id: "settings", name_ar: "الإعدادات", description_ar: "تخصيص بيانات المحل والمخزون والواجهة", is_core: 1, is_enabled: 1 },
];

export const INITIAL_ROLES = [
  { id: "role-manager", name: "Manager", name_ar: "المدير العام", description_ar: "صلاحيات كاملة على كل النظام", is_system: 1 },
  { id: "role-cashier", name: "Cashier", name_ar: "كاشير", description_ar: "تسجيل المبيعات والعملاء فقط", is_system: 1 },
  { id: "role-inventory", name: "Inventory Employee", name_ar: "مسؤول مخزن", description_ar: "إدارة المنتجات وحركات المخزون والمشتريات", is_system: 1 },
  { id: "role-sales", name: "Sales Employee", name_ar: "مسؤول مبيعات", description_ar: "عرض المخزون وتسجيل المبيعات", is_system: 1 },
];

export const INITIAL_PERMISSIONS = [
  // Products
  { code: "products.view", name_ar: "عرض المنتجات", module: "products" },
  { code: "products.create", name_ar: "إضافة منتج", module: "products" },
  { code: "products.update", name_ar: "تعديل منتج", module: "products" },
  { code: "products.delete", name_ar: "حذف منتج", module: "products" },
  // Inventory
  { code: "inventory.view", name_ar: "عرض المخزون", module: "inventory" },
  { code: "inventory.adjust", name_ar: "تسوية المخزون", module: "inventory" },
  // Sales
  { code: "sales.view", name_ar: "عرض المبيعات", module: "sales" },
  { code: "sales.create", name_ar: "تسجيل بيع", module: "sales" },
  { code: "sales.cancel", name_ar: "إلغاء فاتورة بيع", module: "sales" },
  // Purchases
  { code: "purchases.view", name_ar: "عرض المشتريات", module: "purchases" },
  { code: "purchases.create", name_ar: "تسجيل شراء", module: "purchases" },
  { code: "purchases.cancel", name_ar: "إلغاء فاتورة شراء", module: "purchases" },
  // Customers
  { code: "customers.view", name_ar: "عرض العملاء", module: "customers" },
  { code: "customers.create", name_ar: "إضافة عميل", module: "customers" },
  { code: "customers.update", name_ar: "تعديل عميل", module: "customers" },
  { code: "customers.delete", name_ar: "حذف عميل", module: "customers" },
  // Suppliers
  { code: "suppliers.view", name_ar: "عرض الموردين", module: "suppliers" },
  { code: "suppliers.create", name_ar: "إضافة مورد", module: "suppliers" },
  { code: "suppliers.update", name_ar: "تعديل مورد", module: "suppliers" },
  { code: "suppliers.delete", name_ar: "حذف مورد", module: "suppliers" },
  // Reports
  { code: "reports.view", name_ar: "عرض التقارير", module: "reports" },
  // Users
  { code: "users.view", name_ar: "عرض المستخدمين", module: "users" },
  { code: "users.create", name_ar: "إضافة مستخدم", module: "users" },
  { code: "users.update", name_ar: "تعديل مستخدم", module: "users" },
  { code: "users.delete", name_ar: "حذف مستخدم", module: "users" },
  // Settings
  { code: "settings.view", name_ar: "عرض الإعدادات", module: "settings" },
  { code: "settings.update", name_ar: "تعديل الإعدادات", module: "settings" },
  // Backup
  { code: "backup.create", name_ar: "إنشاء نسخة احتياطية", module: "backup" },
  { code: "backup.restore", name_ar: "استرجاع نسخة احتياطية", module: "backup" },
];

export const INITIAL_UNITS = [
  { id: "unit-sqm", name: "متر مربع", symbol: "م²", is_default: 1 },
  { id: "unit-piece", name: "قطعة", symbol: "ق", is_default: 0 },
  { id: "unit-bag", name: "شيكارة", symbol: "شك", is_default: 0 },
  { id: "unit-set", name: "طقم", symbol: "ط", is_default: 0 },
  { id: "unit-box", name: "كرتونة", symbol: "كرتونة", is_default: 0 },
  { id: "unit-can", name: "جركن", symbol: "جركن", is_default: 0 },
];

export const INITIAL_EXPENSE_CATEGORIES = [
  { id: "exp-cat-rent", name: "إيجار", is_system: 1 },
  { id: "exp-cat-electricity", name: "كهرباء ومياه", is_system: 1 },
  { id: "exp-cat-salaries", name: "مرتبات وأجور", is_system: 1 },
  { id: "exp-cat-transport", name: "نقل ومواصلات", is_system: 1 },
  { id: "exp-cat-maintenance", name: "صيانة وضيافة", is_system: 1 },
  { id: "exp-cat-marketing", name: "تسويق ودعاية", is_system: 1 },
  { id: "exp-cat-other", name: "مصاريف أخرى", is_system: 1 },
];

export const INITIAL_CATEGORIES = [
  { id: "cat-ceramic", name: "سيراميك", description: "سيراميك أرضيات وحوائط فرز أول وثاني", is_active: 1 },
  { id: "cat-porcelain", name: "بورسلين", description: "بورسلين هندي وإسباني ومصري عالي الجودة", is_active: 1 },
  { id: "cat-adhesives", name: "مواد لاصقة", description: "لصق سيراميك وأسمنت وعوازل", is_active: 1 },
  { id: "cat-sanitary", name: "أدوات صحية", description: "أحواض وخلاطات ومحابس ودش", is_active: 1 },
  { id: "cat-supplies", name: "مستلزمات تركيب", description: "صلايب وكلبسات وفواصل تمدد", is_active: 1 },
];

export const INITIAL_SUPPLIERS = [
  {
    id: "sup-1",
    name: "شركة النور للتوريدات",
    phone: "01012345678",
    second_phone: "0223456789",
    address: "المنطقة الصناعية، العاشر من رمضان",
    email: "info@el-nour.com",
    balance: 15400,
    notes: "مورد معتمد لمصانع السيراميك والبورسلين",
    is_active: 1,
  },
  {
    id: "sup-2",
    name: "مؤسسة الأمل",
    phone: "01198765432",
    second_phone: null,
    address: "شارع الفجالة، القاهرة",
    email: "amal@supplies.eg",
    balance: 0,
    notes: "توريد المواد اللاصقة والعوازل والأسمنت الأبيض",
    is_active: 1,
  },
  {
    id: "sup-3",
    name: "شركة المتحدة للتجارة",
    phone: "01255566778",
    second_phone: "01099887766",
    address: "طريق مصر إسكندرية الزراعي، طنطا",
    email: "sales@united-trade.com",
    balance: 24000,
    notes: "وكيل أدوات صحية وخلاطات مياه تركي ومحلي",
    is_active: 1,
  },
];

export const INITIAL_CUSTOMERS = [
  {
    id: "cust-1",
    name: "شركة المقاولون",
    phone: "01001122334",
    address: "التجمع الخامس، القاهرة الجديدة",
    balance: 8500, // مديونية عليه
    notes: "عميل منتظم - مشاريع تشطيب فيلات وعمارات",
    is_active: 1,
  },
  {
    id: "cust-2",
    name: "محمود أحمد",
    phone: "01122334455",
    address: "شبرا، القاهرة",
    balance: 0,
    notes: "صنايعي تشطيبات وديكور",
    is_active: 1,
  },
  {
    id: "cust-3",
    name: "محمد للتجارة",
    phone: "01277889900",
    address: "شارع البحر، المحلة الكبرى",
    balance: 3200,
    notes: "محل بيع قطاعي يتعامل بالآجل",
    is_active: 1,
  },
];

export const INITIAL_PRODUCTS = [
  {
    id: "prod-1",
    name: "سيراميك أرضيات 60×60 فرز أول",
    sku: "CER-FL-6060",
    barcode: "622100100101",
    category_id: "cat-ceramic",
    unit_id: "unit-sqm",
    purchase_price: 140,
    selling_price: 185,
    minimum_stock: 50,
    maximum_stock: 500,
    current_stock: 240,
    description: "سيراميك أرضيات ليزر كت مقاوم للخدش فرز أول",
    notes: "الكرتونة تحتوي على 1.44 متر مربع",
    is_active: 1,
  },
  {
    id: "prod-2",
    name: "سيراميك حوائط 30×60 مطابخ وحمامات",
    sku: "CER-WL-3060",
    barcode: "622100100102",
    category_id: "cat-ceramic",
    unit_id: "unit-sqm",
    purchase_price: 120,
    selling_price: 160,
    minimum_stock: 40,
    maximum_stock: 400,
    current_stock: 180,
    description: "سيراميك حوائط ديكور فاخر لمعة كريستال",
    notes: "مناسب للمطابخ والحمامات الحديثة",
    is_active: 1,
  },
  {
    id: "prod-3",
    name: "بورسلين 120×60 أسباني ملمع",
    sku: "POR-FL-12060",
    barcode: "622100100103",
    category_id: "cat-porcelain",
    unit_id: "unit-sqm",
    purchase_price: 320,
    selling_price: 430,
    minimum_stock: 30,
    maximum_stock: 300,
    current_stock: 95,
    description: "بورسلين عالي التحمل لمعة نانو ضد البقع",
    notes: "تخزين أفقي لتجنب الكسر",
    is_active: 1,
  },
  {
    id: "prod-4",
    name: "لاصق سيراميك ممتاز 25 كجم",
    sku: "ADH-T25",
    barcode: "622100100104",
    category_id: "cat-adhesives",
    unit_id: "unit-bag",
    purchase_price: 95,
    selling_price: 130,
    minimum_stock: 20,
    maximum_stock: 200,
    current_stock: 65,
    description: "مونه لاصقة للبورسلين والسيراميك داخلية وخارجية",
    notes: "صلاحية الاستخدام للمنتج طويلة",
    is_active: 1,
  },
  {
    id: "prod-5",
    name: "أسمنت أبيض سوبر 50 كجم",
    sku: "CEM-W50",
    barcode: "622100100105",
    category_id: "cat-adhesives",
    unit_id: "unit-bag",
    purchase_price: 160,
    selling_price: 210,
    minimum_stock: 15,
    maximum_stock: 150,
    current_stock: 42,
    description: "أسمنت أبيض عالي البياض لملء الفواصل والديكور",
    notes: "يحفظ بعيداً عن الرطوبة",
    is_active: 1,
  },
  {
    id: "prod-6",
    name: "مادة عزل مائي وحراري سيكو 15 كجم",
    sku: "ISO-WAT-15",
    barcode: "622100100106",
    category_id: "cat-adhesives",
    unit_id: "unit-can",
    purchase_price: 340,
    selling_price: 450,
    minimum_stock: 8,
    maximum_stock: 80,
    current_stock: 6, // منخفض للتحذير
    description: "عازل مائي للأسطح وأرضيات الحمامات والمطابخ",
    notes: "يحتاج وجهين للحصول على أفضل كفاءة",
    is_active: 1,
  },
  {
    id: "prod-7",
    name: "خلاط مياه شجرة حوض عالي كروم",
    sku: "SAN-MIX-01",
    barcode: "622100100107",
    category_id: "cat-sanitary",
    unit_id: "unit-piece",
    purchase_price: 680,
    selling_price: 950,
    minimum_stock: 5,
    maximum_stock: 50,
    current_stock: 14,
    description: "قلب سيراميك ألماني ضمان 10 سنوات",
    notes: "مع وصلات المياه وطقم التثبيت كامل",
    is_active: 1,
  },
  {
    id: "prod-8",
    name: "حوض حمام ساقط رخام دائري 45 سم",
    sku: "SAN-BAS-45",
    barcode: "622100100108",
    category_id: "cat-sanitary",
    unit_id: "unit-piece",
    purchase_price: 450,
    selling_price: 650,
    minimum_stock: 5,
    maximum_stock: 40,
    current_stock: 0, // نفد للتنبيه
    description: "حوض خزف أبيض عالي الجودة ساقط بالرخامة",
    notes: "مطلوب طلب شحنة جديدة",
    is_active: 1,
  },
  {
    id: "prod-9",
    name: "مستلزمات تركيب كلبسات وصلايب 2 مم (كيس 100 قطعة)",
    sku: "ACC-CLP-02",
    barcode: "622100100109",
    category_id: "cat-supplies",
    unit_id: "unit-box",
    purchase_price: 25,
    selling_price: 40,
    minimum_stock: 30,
    maximum_stock: 300,
    current_stock: 120,
    description: "فواصل تسوية البلاط لضبط استواء السيراميك بدقة",
    notes: "سريعة الاستهلاك مع كل أوردر سيراميك",
    is_active: 1,
  },
];
